project:
  type: website
  execute-dir: project
  resources:
    - staticwebapp.config.json
    - robots.txt
    - CNAME
  render:
    - "*.qmd"
  pre-render: scripts/clean-quarto-temp.R

website:
  title: "ESQlabs R Trainings"
  description: "R training materials and resources from ESQlabs"
  favicon: "resources/favicon.ico"
  site-url: "https://r-training.esqlabs.com/"
  repo-url: "https://github.com/esqLABS/r-packages-training"

execute:
  freeze: auto  # re-render only when source changes
